# Generated by Django 5.1.1 on 2024-09-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_profile_createtime_remove_profile_textarea_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.AddField(
            model_name="profile",
            name="textarea",
            field=models.CharField(
                default="这个人很懒，什么也没留下。", max_length=255, verbose_name="个人简介"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(default="", max_length=255, verbose_name="地址"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="sex",
            field=models.CharField(default="", max_length=255, verbose_name="性别"),
        ),
    ]
