# Generated by Django 5.1.1 on 2024-10-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_profile_bio_profile_textarea_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.FileField(
                default="/avatar/02.png", upload_to="avatar", verbose_name="头像"
            ),
        ),
    ]
